import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/layout/Layout";
import Hero from "@/components/Hero";
import Schedule from "@/components/Schedule";
import Ideatheme from "@/components/IdeathonThema";
import IdeathonFeatures from "@/components/IdeathonFeatures";
import Info from "@/components/Info";
import Judging from "@/components/Judging";
import Sponsor from "@/components/Sponsor/Sponsor";
import FAQ from "@/components/FAQ";
import Seo from "@/components/Seo";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>あまてく×CACアイディアソン</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Seo />
      </Head>
      <main className={styles.main}>
        <Layout>
          <Hero />
          <Ideatheme />
          <IdeathonFeatures />
          <Info />
          <Schedule />
          <Sponsor />
          <FAQ />
        </Layout>
      </main>
    </>
  );
}
